micronaut:
  application:
    name: secureRoutes
  server:
    port: 1234
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/rimfirededb?currentSchema=jwt_auth
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
    username: rimfirededb
    password: mysecretpassword
